language: rust
rust:
  - nightly
  - beta
  - 1.37.0
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

os:
  - linux
  - osx

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
